# Streamlit Secrets Configuration
# This file shows the structure of secrets needed for deployment
# DO NOT commit actual secrets to GitHub!

# Google Gemini AI API Key (optional - for threat analysis)
# GEMINI_API_KEY = "your_gemini_api_key_here"

# Admin Configuration (optional - for admin panel access)
# ADMIN_EMAILS = ["admin@example.com", "owner@example.com"]

# Instructions:
# 1. For local development, create .streamlit/secrets.toml with your actual keys
# 2. For Streamlit Cloud deployment, add these secrets in the app settings
# 3. Never commit actual API keys or sensitive data to version control